// Generated by typings
// Source: https://raw.githubusercontent.com/david-driscoll/rxjs-symbol-typings/b06ca4cc670b9e0f2ace68a339dce38648e10e6c/rxjs-symbol-shim.d.ts
interface Symbol { }
interface SymbolConstructor {
  iterator: symbol;
}
declare var Symbol: SymbolConstructor;
interface Iterable<T> {
    [Symbol.iterator](): Iterator<T>;
}
interface Iterator<T> {
    next(value?: any): IteratorResult<T>;
    return?(value?: any): IteratorResult<T>;
    throw?(e?: any): IteratorResult<T>;
}
